"""all tables

Revision ID: ff2822129d92
Revises: 
Create Date: 2018-04-08 18:34:01.895447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2822129d92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('english',
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    op.create_table('grammar',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('lexical',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vocab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ewe', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('audio', sa.String(length=240), nullable=True),
    sa.Column('image', sa.String(length=240), nullable=True),
    sa.Column('lexical', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_english_assoc',
    sa.Column('vocab_id', sa.Integer(), nullable=True),
    sa.Column('english_word', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['english_word'], ['english.word'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab.id'], )
    )
    op.create_table('vocab_grammar_assoc',
    sa.Column('vocab_id', sa.Integer(), nullable=True),
    sa.Column('grammar_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['grammar_type'], ['grammar.name'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocab_grammar_assoc')
    op.drop_table('vocab_english_assoc')
    op.drop_table('vocab')
    op.drop_table('user')
    op.drop_table('lexical')
    op.drop_table('grammar')
    op.drop_table('english')
    op.drop_table('category')
    # ### end Alembic commands ###
